// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABk2m1aTaM29O6LD1fURAeANiqJj2SmAk',
    appId: '1:1034897656453:web:ea7c24ac6434c07ee437ec',
    messagingSenderId: '1034897656453',
    projectId: 'com-afsal-sparkd',
    authDomain: 'com-afsal-sparkd.firebaseapp.com',
    storageBucket: 'com-afsal-sparkd.firebasestorage.app',
    measurementId: 'G-G1VYEV81XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZFIgXCt9WUavihWfaja7M2bjLzdgDn00',
    appId: '1:1034897656453:android:04ff57aae87c5ca9e437ec',
    messagingSenderId: '1034897656453',
    projectId: 'com-afsal-sparkd',
    storageBucket: 'com-afsal-sparkd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcb0ppFaN3b_c3ZWpdmHYPXJKgMaAiuUE',
    appId: '1:1034897656453:ios:fe64e2fe92a28c3ee437ec',
    messagingSenderId: '1034897656453',
    projectId: 'com-afsal-sparkd',
    storageBucket: 'com-afsal-sparkd.firebasestorage.app',
    iosBundleId: 'com.example.sparkd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcb0ppFaN3b_c3ZWpdmHYPXJKgMaAiuUE',
    appId: '1:1034897656453:ios:fe64e2fe92a28c3ee437ec',
    messagingSenderId: '1034897656453',
    projectId: 'com-afsal-sparkd',
    storageBucket: 'com-afsal-sparkd.firebasestorage.app',
    iosBundleId: 'com.example.sparkd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABk2m1aTaM29O6LD1fURAeANiqJj2SmAk',
    appId: '1:1034897656453:web:c760604ff44b23cde437ec',
    messagingSenderId: '1034897656453',
    projectId: 'com-afsal-sparkd',
    authDomain: 'com-afsal-sparkd.firebaseapp.com',
    storageBucket: 'com-afsal-sparkd.firebasestorage.app',
    measurementId: 'G-R4R7JR3YEV',
  );
}
